export const ADD_USER = "ADD_USER";
export const WRITE_FILTERS = "WRITE_FILTERS";
export const GET_USER_JOBS = "GET_USER_JOBS";
export const SAGA_GET_USER_JOBS = "SAGA_GET_USER_JOBS";
export const RECORDS_NEW_VACANCIES = "RECORDS_NEW_VACANCIES";
export const SAGA_RECORDS_NEW_VACANCIES = "SAGA_RECORDS_NEW_VACANCIES";
